### ISSUE TITLE
Android public install page and other build files

### ISSUE THREAD

**Issue by alashow** [bitrise-io/steps-deploy-to-bitrise-io#23]
Hello.

I wanted to config my bitrise.yml to deploy mappings.xml (proguard mapping file).

First, I changed it to:
```
- deploy-to-bitrise-io:
        inputs:
        - deploy_path: app/build/outputs/mapping/release/mapping.txt
```

Build succeed, but only  mappings.xml was uploaded, apk was missing.

So I tried changing my bitrise.yml to include all build files with compressing:
```
- deploy-to-bitrise-io:
        inputs:
        - deploy_path: app/build/outputs/
        - is_compress: 'true'
```

With this, I got my all files (apk, mappings etc.) but I will also need public install page.
While having custom deploy path, how can I still have public install page?

Thank you.

**Comment by alashow** [comment]
Turns out, I can use same step multiple times.

I changed it to:
```yml
- deploy-to-bitrise-io@1.2.6:
        is_always_run: false
- deploy-to-bitrise-io:
    inputs:
    - deploy_path: app/build/outputs/
    - is_compress: 'true'
```

The fIrst deploy step will upload apks with public install page (if successful), second one will upload build/outputs folder.
