### ISSUE TITLE
Remove is_expand: false from is_compress input

### ISSUE THREAD

**Issue by lhildenST** [bitrise-io/steps-deploy-to-bitrise-io#41]
by forcing is_expand false by default:
```
is_compress: "false"
    opts:
      ...
      is_expand: false
```
I cannot pass in an environment value into this step like this:
```
    - deploy-to-bitrise-io@1.3.5:
        inputs:
        - is_compress: $MY_COMPRESS_OPTION
```
which blows.  When I attempt to do so by specifying `opts: -is_expand: false` on the `is_compress` input, I get:
```bash
Error: Config (path:bitrise.yml) is not valid: failed to cast options value: ([]interface {}{map[interface {}]interface {}{"is_expand":true}})
```

**Comment by viktorbenei** [comment]
>  When I attempt to do so by specifying 

Most likely an indentation issue.

Please try it this way:

```
    - deploy-to-bitrise-io:
        inputs:
        - is_compress: "$MY_COMPRESS_OPTION"
          opts: { is_expand: true }
```

is_compress (the input's key) and `opts` have to be indented to the same "column"
